"use client";

import Link from "next/link";
import { ArrowRight, BookOpen, ShieldCheck, Users } from "lucide-react";

const portals = [
  { title: "Portal Admin", label: "OPERATE", description: "Kelola layanan, orang, jadwal, enrollment, roadmap, dan tagihan dalam satu ruang kerja.", href: "/app/admin", icon: ShieldCheck, tone: "dark" },
  { title: "Ruang Belajar", label: "LEARN", description: "Buka koleksi materi, pantau progress membaca, dan lanjutkan lesson yang sedang kamu kerjakan.", href: "/app/materi", icon: BookOpen, tone: "blue" },
  { title: "Portal Wali Murid", label: "SUPPORT", description: "Pantau program, jadwal, laporan belajar, dan kebutuhan pembayaran anak.", href: "/app/dashboard", icon: Users, tone: "light" },
];

export default function AppIndexPage() {
  return <main className="min-h-screen bg-[#eef3f8] px-4 py-8 text-[#14233a] sm:px-6 lg:px-10 lg:py-12"><div className="mx-auto max-w-6xl"><header className="flex flex-col justify-between gap-6 border-b border-[#c7d4e2] pb-8 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#6a7f98]">Nurman Course / Portal</p><h1 className="mt-3 text-3xl font-black tracking-[-0.05em] sm:text-5xl">Pilih ruang kerja.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#657991]">Masuk ke area yang sesuai dengan tugasmu hari ini. Setiap portal dibuat ringkas agar kamu bisa langsung mulai.</p></div><Link href="/course" className="text-sm font-bold text-[#284970] underline decoration-[#9cb0c4] underline-offset-4 hover:text-[#4a70a9]">Kembali ke halaman pendaftaran</Link></header><section aria-label="Pilihan portal" className="mt-8 grid gap-4 lg:grid-cols-3">{portals.map((portal) => { const Icon = portal.icon; const dark = portal.tone === "dark"; return <article key={portal.title} className={`flex min-h-[20rem] flex-col justify-between rounded-xl border p-6 ${dark ? "border-[#14233a] bg-[#14233a] text-white" : portal.tone === "blue" ? "border-[#b5cbe0] bg-[#e5eef7]" : "border-[#c7d4e2] bg-white"}`}><div><div className={`flex items-center justify-between ${dark ? "text-[#f2c14e]" : "text-[#4a70a9]"}`}><span className="grid h-11 w-11 place-items-center rounded-lg bg-current/10"><Icon size={22} aria-hidden="true" /></span><span className="font-mono text-[10px] font-bold tracking-[0.16em]">{portal.label}</span></div><h2 className="mt-8 text-xl font-black tracking-[-0.03em]">{portal.title}</h2><p className={`mt-3 text-sm leading-6 ${dark ? "text-[#b8c5d6]" : "text-[#657991]"}`}>{portal.description}</p></div><Link href={portal.href} className={`mt-8 inline-flex min-h-11 items-center justify-center gap-2 rounded-lg px-4 text-sm font-bold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 ${dark ? "bg-[#f2c14e] text-[#14233a] hover:bg-[#f6d67f] focus-visible:ring-[#f2c14e]" : "bg-[#284970] text-white hover:bg-[#1d395a] focus-visible:ring-[#4a70a9]"}`}>Masuk ke portal <ArrowRight size={16} aria-hidden="true" /></Link></article>; })}</section></div></main>;
}
